# GET ALL REQUEST
GET http://localhost:8000/items


###


# GET ONE 
GET http://localhost:8000/students/670acbc21219e7aa8776683b


###

# POST REQUEST
POST http://localhost:8000/students
Content-Type: application/json

{
  "name": "Dayton",
  "class": "new class"
}


###

# DELETE REQUEST

DELETE http://localhost:8000/students/670acbc21219e7aa8776683b


###

# PATCH UPDATE REQUEST


PATCH http://localhost:8000/students/670c673b7cb49e6e796f896c
Content-Type: application/json

{
  "name": "BB",
  "class": "ASL"
}

